# Generated by Django 3.2 on 2023-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
